In [52]:
import numpy as np
import matplotlib.pyplot as plt

In [53]:
x = np.array([0.0, 2.5, 5.0, 12.5, 20.0, 20.0, 27.5, 35.0])
y = np.array([20.0, 14.2, 0.0, -10.0, -15.0, -10.0, 0.0, 14.2])

In [54]:
def get_axvline(_from=0, _to=0.5, _ymin=0, _ymax=1):
    _span = _ymax - _ymin
    
    def positive_axis():
        return _from < _to
    
    ymin_ = ymax_ = None
    
    if positive_axis():
        ymin_ = (_from + abs(_ymin))/float(_span)
        ymax_ = (_to + abs(_ymin))/float(_span)
    else:
        ymin_ = (_to + abs(_ymin))/float(_span)
        ymax_ = (_from + abs(_ymin))/float(_span)

    return ymin_, ymax_ 

In [61]:
def plot_original_data(_x, _horizontal=None, title='Sinal X', savefig=False, fname='images/default.png'):
    if not (_horizontal == None):
        _horizontal = list(range(len(_x)))
    plt.plot(_horizontal, _x, 'o')
    for eixo_x in _horizontal:
        min_y, max_y = get_axvline(0, _x[eixo_x], min(_x), max(_x))
        plt.axvline(x=eixo_x, ymin=min_y, ymax=max_y, color='k')
    
    plt.xlabel('Amostras')
    plt.ylabel('Amplitude')
    plt.title(title)
    if savefig:
        plt.savefig(fname)
    else:
        plt.show()
    plt.close()

In [62]:
horizontal = list(range(len(x)))
plot_original_data(_x=x, _horizontal=horizontal, title='Sinal X', savefig=True, fname='../propostas-trabalho-final/imagens/sinal_x.png')

In [57]:
def get_even_periodic_extension_from_signal(x, n=2):
    return np.tile(x, n)

In [58]:
def get_odd_periodic_extension_from_signal(x, n=2):
    result = x
    flipped = np.flipud(x)
    for i in range(n-1):
        result = np.concatenate((result, flipped))
        flipped = np.flipud(flipped)
    return result

In [67]:
def get_mirror_odd_periodic_extension_from_signal(x, n=2):
    result = x
    flipped = np.flipud(-1*x)
    for i in range(n-1):
        result = np.concatenate((result, flipped))
        flipped = np.flipud(-1*flipped)
    return result

In [64]:
horizontal = list(range(-len(x), 2*len(x)))
eixo_x_even = get_even_periodic_extension_from_signal(x, 3)
plot_original_data(eixo_x_even, horizontal, title='Extensao periodica X', savefig=True, fname='../propostas-trabalho-final/imagens/extensao_x.png')

In [72]:
repetitions = 3
eixo_x_odd = get_odd_periodic_extension_from_signal(x, repetitions)

In [73]:
horizontal = np.array(list(range(len(eixo_x_odd)))) - len(x)

In [74]:
plot_original_data(eixo_x_odd, horizontal, title='Extensao periodica par de X', savefig=True, fname='../propostas-trabalho-final/imagens/extensao_par_x.png')

D:\Users\Pablo\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  from ipykernel import kernelapp as app


In [71]:
repetitions = 3
eixo_x_odd_mirror = get_mirror_odd_periodic_extension_from_signal(x, repetitions)
horizontal = np.array(list(range(len(eixo_x_odd_mirror)))) - len(x)
plot_original_data(eixo_x_odd_mirror, horizontal, title='Extensao periodica impar de X', savefig=True, fname='../propostas-trabalho-final/imagens/extensao_impar_x.png')

D:\Users\Pablo\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  from ipykernel import kernelapp as app


SINAL Y

In [63]:
horizontal = list(range(len(y)))
plot_original_data(_x=y, _horizontal=horizontal, title='Sinal Y', savefig=True, fname='../propostas-trabalho-final/imagens/sinal_y.png')

In [66]:
horizontal = list(range(-len(y), 2*len(y)))
plot_original_data(get_even_periodic_extension_from_signal(y, 3), horizontal, title='Extensao periodica par de Y', savefig=True, fname='../propostas-trabalho-final/imagens/extensao_par_y.png')

In [76]:
horizontal = list(range(-len(y), 2*len(y)+2))
plot_original_data(get_mirror_odd_periodic_extension_from_signal(y, 3), horizontal, title='Extensao periodica impar de Y', savefig=True, fname='../propostas-trabalho-final/imagens/extensao_impar_y.png')

In [87]:
yy=get_mirror_odd_periodic_extension_from_signal(y, 3)
(yy)

array([ 20. ,  14.2,   0. , -10. , -15. , -10. ,   0. ,  14.2, -14.2,
        -0. ,  10. ,  15. ,  10. ,  -0. , -14.2, -20. ,  20. ,  14.2,
         0. , -10. , -15. , -10. ,   0. ,  14.2])

In [86]:
(range(-len(y), 2*len(y)))

[-8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15]

In [197]:
x_hat = np.fft.fft(x)
y_hat = np.fft.fft(y)

A transformada de Fourier do sinal X é composta de valores complexos

In [203]:
x_hat

array([ 122.50000000 +0.j        ,  -16.46446609+50.78427125j,
        -12.50000000+25.j        ,  -23.53553391 +5.78427125j,
        -17.50000000 +0.j        ,  -23.53553391 -5.78427125j,
        -12.50000000-25.j        ,  -16.46446609-50.78427125j])

In [204]:
y_hat

array([ 13.40000000 +0.00000000e+00j,  69.22396821 -2.48689958e-14j,
         5.00000000 +0.00000000e+00j,   0.77603179 +2.84217094e-14j,
        -3.40000000 +0.00000000e+00j,   0.77603179 +2.48689958e-14j,
         5.00000000 +0.00000000e+00j,  69.22396821 -2.84217094e-14j])

In [207]:
from scipy import fftpack

In [208]:
fftpack.dct(x)

array([ 245.        , -129.82191206,    8.44623199,  -10.69124485,
         17.67766953,   -8.17540614,   -7.32537816,    3.88987995])